### ISSUE TITLE
Cannot use copy shortcut on document page

### ISSUE THREAD

**Issue by andy3520** [rayepps/radash-docs#36]
### Environment:
1. MacbookPro M1
2. MacOS: 12.5.1
3. Chrome: Version 104.0.5112.101 (Official Build) (arm64)
### Issue:
The shortcut key to copy (Cmd + C) is caught by the search function so when every I use the copy shortcut, the search bar is getting focus and the content was not copied.
### Reproduce:
Video: https://streamable.com/320vpm
1. Goto any document page. Eg: https://radash-docs.vercel.app/docs/string-dash
2. Select a command or a content on the document page. 
3. Use Cmd + C to copy.
4. The search input is focused.
5. Try to paste the content to see it not getting copy yet.
### Expected behavior:
1. Can use Cmd + C to copy the content on document page.
2. The search input not getting focus when press Cmd + C.

Edit 1:
Seem like every shortcut start with `Cmd` will make the focus go to search input element.

**Comment by sodiray** [comment]
This has been fixed in #40 (huge thanks go to @qqqrppp ❤️)
